
function getCategories() {

var cats = [
  {
   "category_name": " Accessories (General) ",
   "category_name_ar": "  ???????? ???? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0.09,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Adapters ",
   "category_name_ar": " ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0.09,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " All Audio/Video ",
   "category_name_ar": " ???? ????? ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0.09,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Auto Parts ",
   "category_name_ar": " ??? ?????? ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Battery ",
   "category_name_ar": " ??????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.12,
   "margin_aqaba": 0.15,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Belts and Wallets ",
   "category_name_ar": " ????? ? ????? ",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Bicycles (including delivery tricycles), not motorized. ",
   "category_name_ar": "?????? ????? ??? ?????? ??????? ???? ? ???? ??????? ",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 8
 },
 {
   "category_name": " Binoculars/Telescopes ",
   "category_name_ar": " ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Books ",
   "category_name_ar": " ???? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Bracelett ",
   "category_name_ar": "  ????? ???? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Brooms and brushes ",
   "category_name_ar": "????? ???????",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Cables/Adapters ",
   "category_name_ar": " ?????  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Camera Digital ",
   "category_name_ar": " ?????? ????? ",
   "customs": 0,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Camera for documents ",
   "category_name_ar": " ?????? ??????? ",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Camera Lens ",
   "category_name_ar": " ???? ?????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Capacitor (Fixed) ",
   "category_name_ar": " ???????? ??????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Carpets ",
   "category_name_ar": " ???? ",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Carrying Case ",
   "category_name_ar": " ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 4
 },
 {
   "category_name": " Charger ",
   "category_name_ar": " ???? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Cleaning Agents/Detergents ",
   "category_name_ar": " ?????? ",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Clothing ",
   "category_name_ar": " ????? ",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 1.18,
   "min_side_length": 1
 },
 {
   "category_name": " Clothing accessories  Leather gloves, mittens and mitts) ",
   "category_name_ar": " ? ????? ????? ?  ???????? ??????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 1.35,
   "min_side_length": 1
 },
 {
   "category_name": " Clothing Dresses or Suits ",
   "category_name_ar": " ????? ??????? ???????? ",
   "customs": 0.25,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 1.35,
   "min_side_length": 1
 },
 {
   "category_name": " Computer Card ",
   "category_name_ar": "? ????? ?????? ?????? ???????? ??????? ?? ????????",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Computer Case No power Supply  ",
   "category_name_ar": " ????? ??????? ???? ???? ???????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 10
 },
 {
   "category_name": " Computer Case With power Supply  ",
   "category_name_ar": " ????? ??????? ?? ???? ???????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 10
 },
 {
   "category_name": " Computer Fan  ",
   "category_name_ar": " ????? ???????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Computer Parts ",
   "category_name_ar": " ??? ??????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Computer Replacement Parts ",
   "category_name_ar": " ???  ???? ??????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " converters (Static) ",
   "category_name_ar": " ?????? ?????? ????? ",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " cosmetics or toilet preparations ",
   "category_name_ar": " ???? ??????? ?? ?????? ??????? ",
   "customs": 0.12,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.16,
   "margin_aqaba": 0.16,
   "special_tax": 0.05,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Cover ",
   "category_name_ar": " ??? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 1.37,
   "min_side_length": 1
 },
 {
   "category_name": " CPU/Processor ",
   "category_name_ar": "? ????? ?????? ?????? ???????? ??????? ?? ????????",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 3
 },
 {
   "category_name": " Dental Care ",
   "category_name_ar": " ??????? ???????? ",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Drilling, threading or tapping tools ",
   "category_name_ar": "? ????? ???? ??????",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Electric Applieances ",
   "category_name_ar": " ??????? ?????????? ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Electric Scooter ",
   "category_name_ar": " ???????????? ",
   "customs": 0,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Electronic calculators ",
   "category_name_ar": "? ???? ????? ???????????? ???????? ??? ????? ??????? ???? ????? ?????? ??????????",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Exercise equipment for general physical exercise, gymnastics or athletics ",
   "category_name_ar": "????? ?????? ??????? ??????? ???????? ?????? ?????",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " FAN ",
   "category_name_ar": " ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Fats and oils and their fractions, of fish, other than liver oils ",
   "category_name_ar": "? ???? ????? ????????? ? ?? ????? ??? ??? ?????",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Fertilizers ",
   "category_name_ar": " ????? ",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Flash Drive/ SD Card ",
   "category_name_ar": " ???? ???? / ????? ???????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Food/Chocolate/Candy ",
   "category_name_ar": " ?????? / ?????????? / ????? ",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Food/Chocolate/Candy US Made ",
   "category_name_ar": " ?????? / ?????????? / ????? ???????? ??????? ??? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Game Pad ",
   "category_name_ar": " ???? ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Game PC or Console ",
   "category_name_ar": " ???? / ??? ???? ?????? ????? PC  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Glass Wear ",
   "category_name_ar": " ??? ?????? ",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Gloves (fabric) ",
   "category_name_ar": " ?????? ?? ???? ",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Graphics Card ",
   "category_name_ar": "? ????? ?????? ?????? ???????? ??????? ?? ????????",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Hair Preparations (Shampoo etc) ",
   "category_name_ar": "???????? ??????? ?????? .",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.12,
   "margin_aqaba": 0.12,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Hair-removing appliances ",
   "category_name_ar": "? ????? ????? ?????",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " HardDrives External ",
   "category_name_ar": " ????? ???? ?????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " HardDrives Internal ",
   "category_name_ar": " ????? ???? ?????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Hats ",
   "category_name_ar": " ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Headphones & earphones, w or w/o microphone ",
   "category_name_ar": "?????????? ??? ??????????? ??? ?????????? ? ??? ??????? ????? ?????? ?????",
   "customs": 0.25,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Headset ",
   "category_name_ar": " ????? ??? ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Health and Personal Care ",
   "category_name_ar": " ?????? ??? ",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.16,
   "margin_aqaba": 0.16,
   "special_tax": 0.05,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Health and Personal Care (Liquids) ",
   "category_name_ar": " ?????? ??? - ???? ",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.16,
   "margin_aqaba": 0.16,
   "special_tax": 0.05,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Helmet Motor Cycle ",
   "category_name_ar": " ???? ????? ?????  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Helmet Sports Leisure ",
   "category_name_ar": " ???? ??????? ??????  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Jewelry - Not Real ",
   "category_name_ar": " ??????? ??????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Joystick ",
   "category_name_ar": " ??? ??????  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 3
 },
 {
   "category_name": " Keyboard/Mouse ",
   "category_name_ar": " ???? ???????? / ??????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 4
 },
 {
   "category_name": " kitchenware and Tableware ",
   "category_name_ar": "  ????? ????? ?????  ",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Knee pads ",
   "category_name_ar": "?????? ?????",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " leather clothes ",
   "category_name_ar": " ????? ?????  ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0.08,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 1.37,
   "min_side_length": 1
 },
 {
   "category_name": " Lighting or visual signalling equipment ",
   "category_name_ar": "? ????? ????? ?? ????? ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Machine-tools for working stone, ceramics, concrete, asbestos-cement , glass ",
   "category_name_ar": "??? ???? ???? ????? ?? ????? ?? ???????? ?? ???? ?????? ??????? (?????????) ???????? ?? ???? ?????? ???????? ???????? ?? ???? ?????? ??? ??????",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Magazines ",
   "category_name_ar": " ?????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Medical Apparatus 9022 ",
   "category_name_ar": " ????? ????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Memory ",
   "category_name_ar": " ?????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " microphone and one or more loudspeakers ",
   "category_name_ar": "???? ????? ?? ????? ??? \" ??????? \" ????? ?? ???? ?? ?????? ????? ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 5
 },
 {
   "category_name": " Microscope ",
   "category_name_ar": " ????  ",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Mobile Accessory ",
   "category_name_ar": " ?????? ?????? ??????  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Mobile Phone ",
   "category_name_ar": " ?????? ???????  ",
   "customs": 0,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Monitor  ",
   "category_name_ar": " ???? ???????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 7
 },
 {
   "category_name": " Motherboard ",
   "category_name_ar": "? ????? ?????? ?????? ???????? ??????? ?? ????????",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 3
 },
 {
   "category_name": " Mouse Pad ",
   "category_name_ar": " ???? ???  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Mouse/Keyboard ",
   "category_name_ar": " ?????? / ???? ????????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 3
 },
 {
   "category_name": " Musical Instruments ",
   "category_name_ar": " ????? ????????  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0.05,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Neck Tie ",
   "category_name_ar": " ????? ??? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Network Router/Adapter ",
   "category_name_ar": "????? ????????? ?? ???? ????? ?? ??????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Notebook ",
   "category_name_ar": " ?????? ",
   "customs": 0,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0.09,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 4
 },
 {
   "category_name": " Office Equipment  ",
   "category_name_ar": "  ????? ????    ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Office or school supplies ",
   "category_name_ar": " ??????? ",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Pasta (Other - not stuffed) ",
   "category_name_ar": " ??????? ??? ????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Pasta (Stuffed), whether or not cooked or otherwise prepared ",
   "category_name_ar": " ??????? ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " PCs ",
   "category_name_ar": " ????? ?????????  ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Perfume ",
   "category_name_ar": " ??? ",
   "customs": 0.12,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.16,
   "margin_aqaba": 0.12,
   "special_tax": 0.05,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Perfume - US Made ",
   "category_name_ar": " ??? ",
   "customs": 0,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0.05,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Playstation ",
   "category_name_ar": " ???? ?????  ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Polyacetals, other polyethers and epoxide resins, in primary forms; polycarbonates, alkyd resins ",
   "category_name_ar": "???? ???????? ????? ?????? ??? ???????? ?????????? ? ???????? ??????? ? ???? ???????",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Power Suppy ",
   "category_name_ar": " ???? ?????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Printer ",
   "category_name_ar": " ????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Projectors ",
   "category_name_ar": " ???? ???? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Protein concentrates and textured protein substances, other ",
   "category_name_ar": "?????? ?????? ????? ???????? ",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Rangefinders ",
   "category_name_ar": "? ?????? ???????",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Real Jewelry ",
   "category_name_ar": " ??????? ??? ???? ?????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Scanner ",
   "category_name_ar": " ???? ???? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Seeds (for planting) ",
   "category_name_ar": " ???? ??????? ",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Shampoos ",
   "category_name_ar": " ????? ",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Shoes ",
   "category_name_ar": " ?????  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 1.37,
   "min_side_length": 1
 },
 {
   "category_name": " Software ",
   "category_name_ar": " ??????? ",
   "customs": 0,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Sound recording or reproducing apparatus .  ",
   "category_name_ar": "????? ????? ?? ????? ?????",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Spare Parts ",
   "category_name_ar": " ??? ???? ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Speaker ",
   "category_name_ar": " ?????? ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 5
 },
 {
   "category_name": " Sporting Goods  ",
   "category_name_ar": " ????? ????????  ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Sunglasses ",
   "category_name_ar": "? ?????? ?????",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Tablet ",
   "category_name_ar": " ??? ???? ",
   "customs": 0,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Tools ",
   "category_name_ar": " ??? ?????? ",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " ToothBrush ",
   "category_name_ar": " ????? ???????  ",
   "customs": 0.12,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Toys ",
   "category_name_ar": " ????? ",
   "customs": 0.35,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Trays, dishes, plates, cups and the like ",
   "category_name_ar": "? ????? ?????? ?????? ??? ???????",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " T-shirts, singlets and other vests, knitted or crocheted. ",
   "category_name_ar": "????? ?? ??? \"?? ????\" ?????? ????? ?????? ?? ?????? ??? ??????? ? ?? ?????? ?? ??????",
   "customs": 0.25,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " TV  ",
   "category_name_ar": " ???? ?????  ",
   "customs": 0.25,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " US Made Cosmetics ",
   "category_name_ar": " ?????? ????????? ?????|????? ????? ",
   "customs": 0,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.16,
   "margin_aqaba": 0.16,
   "special_tax": 0.05,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " US Made Products ",
   "category_name_ar": " ?????? ?????????  ",
   "customs": 0,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.1,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Vitamins ",
   "category_name_ar": " ??????? ",
   "customs": 0.15,
   "tax_aqaba": 0,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Watch (Mechanical display only) ",
   "category_name_ar": " ???? ??? ????????? ",
   "customs": 0.15,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.09,
   "margin_aqaba": 0.1,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 },
 {
   "category_name": " Watch/Sports watches/wearable gear ",
   "category_name_ar": " ???? / ????? ??????? / ???? ???????? ??????? ",
   "customs": 0.35,
   "tax_aqaba": 0.07,
   "tax_amm": 0.16,
   "margin_amm": 0.08,
   "margin_aqaba": 0.09,
   "special_tax": 0,
   "us_tax": 0,
   "cap_aqaba": 999,
   "cap_amm": 999,
   "min_side_length": 1
 }
]

return cats;
}

module.exports.getCategories = getCategories;
